language: node_js
node_js:
  - '8'
  - '4'

env:
  - ESLINT_VERSION=4

matrix:
  include:
  - env: ESLINT_VERSION=4
    node_js: 8
  - env: ESLINT_VERSION=4
    node_js: 4

before_install:
  - 'nvm install-latest-npm'

install:
  - npm install

script:
  - 'npm test'