language: node_js
node_js:
  - '8'
  - '4'

env:
  - ESLINT_VERSION=4

matrix:
  include:
  - env: ESLINT_VERSION=4
    node_js: 8
  - env: ESLINT_VERSION=4
    node_js: 8

install:
  - npm install
  - npm install --no-save eslint@$ESLINT_VERSION --ignore-scripts

script:
  - 'npm test'